language: node_js
warnings_are_errors: false
node_js:
  - lts/dubnium
cache: yarn
branches:
  only:
    - dev
    - master
script:
  - yarn deploy
notifications:
  email:
    - dev-notifications@noblockno.party
