language: node_js
node_js:
  - '8.11.4'
cache: yarn
branches:
  only:
    - travis
    - dev
    - master
script:
  - yarn start
  - $(npm bin)/cypress run --record
  - yarn deploy
notifications:
  email:
    - dev-notifications@noblockno.party
